
-- Candiate Key Creation

ALTER TABLE STAFF_DETAILS ADD UNIQUE KEY CK_STAFF_NO (STAFF_NO);

ALTER TABLE STAFF_DETAILS ADD UNIQUE KEY CK_EMAIL_ID (EMAIL_ID);

ALTER TABLE STAFF_DETAILS ADD UNIQUE KEY CK_AADHAR_NO (AADHAR_NO);

ALTER TABLE STAFF_DETAILS ADD UNIQUE KEY CK_PASSPORT_NO (PASSPORT_NO);


-- To view the unique Constraints

SELECT * FROM information_schema.table_constraints
where table_name = 'staff_details';