SELECT "GREAT LEARNING" As GL;

SELECT LTRIM (RTRIM ('   Hello World   '));

SELECT CONCAT("GREAT LEARNING", " ", "TRAINING PROGRAMS") As GL;

SELECT SUBSTRING(
	CONCAT(
	"GREAT LEARNING", " ", "TRAINING PROGRAMS"
	), 16, 8
) 
As GL;


