drop table IF EXISTS STUDENTS_BATCH_1;
drop table IF EXISTS STUDENTS_BATCH_2;

CREATE TABLE STUDENTS_BATCH_1
(
STUDENT_ID    VARCHAR(10),
STUDENT_NAME   VARCHAR(20)
);

CREATE TABLE STUDENTS_BATCH_2
(
STUDENT_ID    VARCHAR(10),
STUDENT_NAME   VARCHAR(20)
);


INSERT INTO STUDENTS_BATCH_1 (STUDENT_ID, STUDENT_NAME) VALUES ('10', 'Andrew');
INSERT INTO STUDENTS_BATCH_1 (STUDENT_ID, STUDENT_NAME) VALUES ('20', 'Martin');
INSERT INTO STUDENTS_BATCH_1 (STUDENT_ID, STUDENT_NAME) VALUES ('30', 'Anne');

INSERT INTO STUDENTS_BATCH_2 (STUDENT_ID, STUDENT_NAME) VALUES ('20', 'Martin');
INSERT INTO STUDENTS_BATCH_2 (STUDENT_ID, STUDENT_NAME) VALUES ('30', 'Anne');
INSERT INTO STUDENTS_BATCH_2 (STUDENT_ID, STUDENT_NAME) VALUES ('40', 'Leo');