-- Wont work with MySQL
/*
select STUDENT_ID, STUDENT_NAME from STUDENTS_BATCH_1 A 
INTERSECT 
select STUDENT_ID, STUDENT_NAME from STUDENTS_BATCH_1 B
*/

-- Version 1 - Usage of Inner Join
-- Intersect using Inner Join - Using Keyword
SELECT STUDENT_ID, STUDENTS_BATCH_1.STUDENT_NAME FROM STUDENTS_BATCH_1 INNER JOIN STUDENTS_BATCH_2 USING (STUDENT_ID);


SELECT STUDENT_ID, STUDENTS_BATCH_1.STUDENT_NAME FROM STUDENTS_BATCH_1 INNER JOIN STUDENTS_BATCH_2 USING (STUDENT_ID, STUDENT_NAME);

-- Intersect using Inner Join - ON Keyword
SELECT A.STUDENT_ID, A.STUDENT_NAME FROM STUDENTS_BATCH_1 As A INNER JOIN STUDENTS_BATCH_2 As B ON (A.STUDENT_ID = B.STUDENT_ID AND A.STUDENT_NAME = B.STUDENT_NAME);

-- Version 2 - Usage of Sub-Query
-- Intersect using Sub-Query and IN
select STUDENT_ID, STUDENT_NAME from STUDENTS_BATCH_1 As A where ( 
	A.STUDENT_ID IN (Select STUDENT_ID from STUDENTS_BATCH_2) AND
    A.STUDENT_NAME IN (Select STUDENT_NAME from STUDENTS_BATCH_2) 
);