-- Step 1
-- Do a Left Join between A and B
SELECT STUDENT_ID, STUDENT_NAME FROM STUDENTS_BATCH_1 As A
LEFT JOIN STUDENTS_BATCH_2 As B USING (STUDENT_ID, STUDENT_NAME);

-- Step 2
-- Expand the left join for tables A and B
SELECT A.STUDENT_ID, A.STUDENT_NAME, B.STUDENT_ID, B.STUDENT_NAME FROM STUDENTS_BATCH_1 As A
LEFT JOIN STUDENTS_BATCH_2 As B USING (STUDENT_ID, STUDENT_NAME);

-- Step 3
-- Filter the join so that null records present on the counter-par will be returned
SELECT A.STUDENT_ID, A.STUDENT_NAME, B.STUDENT_ID, B.STUDENT_NAME FROM STUDENTS_BATCH_1 As A
LEFT JOIN STUDENTS_BATCH_2 As B USING (STUDENT_ID, STUDENT_NAME)
WHERE B.STUDENT_ID IS NULL;

-- Step 4
-- Remove the redundant columns
SELECT STUDENT_ID, STUDENT_NAME FROM STUDENTS_BATCH_1
LEFT JOIN STUDENTS_BATCH_2 USING (STUDENT_ID, STUDENT_NAME)
WHERE STUDENTS_BATCH_2.STUDENT_ID IS NULL;


