drop table IF EXISTS STAFF_DETAILS;


CREATE TABLE STAFF_DETAILS(
  STAFF_NO VARCHAR(30),
  FIRST_NAME 	VARCHAR(50),
  LAST_NAME VARCHAR(50),
  DESIGNATION VARCHAR(50),
  EMAIL_ID VARCHAR(50),
  AADHAR_NO BIGINT,
  PASSPORT_NO VARCHAR(50)
);

INSERT INTO STAFF_DETAILS (STAFF_NO, FIRST_NAME, LAST_NAME, DESIGNATION, EMAIL_ID, AADHAR_NO, PASSPORT_NO) VALUES ('S-001', 'Divya', '', 'Manager', 'divya@gl.com', 123423453456, 'DA12345');

INSERT INTO STAFF_DETAILS (STAFF_NO, FIRST_NAME, LAST_NAME, DESIGNATION, EMAIL_ID, AADHAR_NO, PASSPORT_NO) VALUES ('S-002', 'Christopher', '', 'HR', 'christopher@gl.com', 234534564567, 'CR23456');

INSERT INTO STAFF_DETAILS (STAFF_NO, FIRST_NAME, LAST_NAME, DESIGNATION, EMAIL_ID, AADHAR_NO, PASSPORT_NO) VALUES ('S-003', 'Ramesh', 'Kumar', 'Admin', 'ramesh.kumar@gl.com', 345645675678, 'RK34567');

INSERT INTO STAFF_DETAILS (STAFF_NO, FIRST_NAME, LAST_NAME, DESIGNATION, EMAIL_ID, AADHAR_NO, PASSPORT_NO) VALUES ('S-004', 'Vidhya', 'Pawan', 'Engineer', 'vidhya.pawan@gl.com', 456756786789, 'VP45678');

