DROP TABLE IF EXISTS CLIENT_RENTAL_AGREEMENT;


CREATE TABLE CLIENT_RENTAL_AGREEMENT(
  C_NO VARCHAR(30),
  PROPERTY_ID VARCHAR(50),
  AGREEMENT_DESCRIPTION VARCHAR(100)
);

INSERT INTO CLIENT_RENTAL_AGREEMENT (C_NO, PROPERTY_ID, AGREEMENT_DESCRIPTION) VALUES ('C-001', 'P-001', 'New agreement is still in the process');

INSERT INTO CLIENT_RENTAL_AGREEMENT (C_NO, PROPERTY_ID, AGREEMENT_DESCRIPTION) VALUES ('C-002', 'P-003', 'Existing agreement needs to be revised');

