drop table IF EXISTS PAYMENT_TRANSACTIONS;

CREATE TABLE PAYMENT_TRANSACTIONS
(
  ID INT,
  CUSTOMER_NAME   VARCHAR(25),
  AMOUNT			DECIMAL(10,2),	
  TRANSACTION_TYPE		VARCHAR(10)
);


INSERT INTO PAYMENT_TRANSACTIONS VALUES (1, 'John', 1000,'CREDIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (2, 'James', 1200,'DEBIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (3, 'Linda', 300,'DEBIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (4, 'Linda', 7000,'CREDIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (5, 'James', 3550,'CREDIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (6, 'John', 750,'DEBIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (7, 'John', 300,'DEBIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (8, 'Linda', 550,'CREDIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (9, 'James', 450,'DEBIT');
INSERT INTO PAYMENT_TRANSACTIONS VALUES (10, 'Linda', 250,'CREDIT');


-- Step-1
select * from PAYMENT_TRANSACTIONS ORDER BY CUSTOMER_NAME;

-- Step-2
select AMOUNT, (-1 * AMOUNT) AS AMOUNT_2 from PAYMENT_TRANSACTIONS;

-- Step-3 (Version 1)
-- Usage of WHEN Conditions
select PT.*, 
	CASE
		WHEN (TRANSACTION_TYPE = 'CREDIT') THEN Amount
    WHEN (TRANSACTION_TYPE = 'DEBIT') THEN Amount * -1
	END As Amount_2
from PAYMENT_TRANSACTIONS As PT;

-- Step-3 (Version 2)
-- Usage of WHEN and ELSE
select PT.*, 
	CASE
		WHEN (TRANSACTION_TYPE = 'CREDIT') THEN Amount
    ELSE Amount * -1
	END As Amount_2
from PAYMENT_TRANSACTIONS As PT;

-- Step 4 (Optional)
select PT.*, 
	CASE
		WHEN (TRANSACTION_TYPE = 'CREDIT') THEN Amount
    ELSE Amount * -1
	END As Amount_2
from PAYMENT_TRANSACTIONS As PT
ORDER BY CUSTOMER_NAME ASC, TRANSACTION_TYPE ASC;

-- Step 4a( Optional)

select (3550 + (-1200) + (-450)) As "James", 
(-450 + (1000) + (-300)) As "John",
(7000 + (550) + (250) + (-300)) As "Linda";

-- Step-5
select Customer_Name,
	sum(
    CASE
      WHEN (TRANSACTION_TYPE = 'CREDIT') THEN Amount
      WHEN (TRANSACTION_TYPE = 'DEBIT') THEN Amount * -1
    END
  ) As Amount_2
from PAYMENT_TRANSACTIONS As Acc
GROUP BY Customer_Name;
