drop table IF EXISTS SAVINGS_ACCOUNT;

CREATE TABLE SAVINGS_ACCOUNT
(
  ACCOUNT_NO INT,
  NAME VARCHAR(50),
  BALANCE_AMOUNT DECIMAL (10, 2)
);

drop table IF EXISTS CUSTOMER_RECENT_LOG;

CREATE TABLE CUSTOMER_RECENT_LOG
(
  ACCOUNT_NO INT,
  COMMENTS VARCHAR(500)
);


INSERT INTO SAVINGS_ACCOUNT (ACCOUNT_NO, NAME, BALANCE_AMOUNT) VALUES 
(12345, "Raghu", 10000.00);

INSERT INTO CUSTOMER_RECENT_LOG (ACCOUNT_NO, COMMENTS) VALUES (12345, "Initial Deposit");

INSERT INTO SAVINGS_ACCOUNT (ACCOUNT_NO, NAME, BALANCE_AMOUNT) VALUES 
(23456, "Kishore", 5000.00);

INSERT INTO CUSTOMER_RECENT_LOG (ACCOUNT_NO, COMMENTS) VALUES (23456, "Initial Deposit");


